-- ======================= --
-- 	   Database Enums     --
-- ======================= --
CREATE TYPE task_status AS ENUM ('Backlog', 'Todo', 'In Progress', 'Review', 'Complete');
CREATE TYPE task_priority AS ENUM ('Low', 'Medium', 'High');
CREATE TYPE member_roles AS ENUM ('Admin', 'Member', 'Viewer');

-- ======================= --
-- 	   Database Tables     --
-- ======================= --
CREATE TABLE Users (
UserId INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
FirstName VARCHAR(100) NOT NULL,
LastName VARCHAR(100) NOT NULL, 
email TEXT UNIQUE NOT NULL,
passwordHash TEXT NOT NULL,
profileImage TEXT,
createdAt TIMESTAMP DEFAULT NOW(),
updatedAt TIMESTAMP DEFAULT NOW(),
PRIMARY KEY (UserId)
);

CREATE TABLE Projects (
ProjectId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ProjectName VARCHAR (200) NOT NULL,
Description TEXT,
OwnerId INT NOT NULL,
createdAt TIMESTAMP DEFAULT NOW(),
updatedAt TIMESTAMP DEFAULT NOW(),
CONSTRAINT fk_user FOREIGN KEY (OwnerId) REFERENCES Users(UserId)
);

CREATE TABLE ProjectMembers (
MembersId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ProjectId INT NOT NULL,
UserId INT NOT NULL,
Roles member_roles NOT NULL DEFAULT 'Member',
JoinedAt TIMESTAMP DEFAULT NOW(),
CONSTRAINT fk_user FOREIGN KEY (UserId) REFERENCES Users(UserId),
CONSTRAINT fk_project FOREIGN KEY (ProjectId) REFERENCES Projects(ProjectId)
);

CREATE TABLE Tasks (
TaskId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
ProjectId INT NOT NULL,
Status task_status NOT NULL DEFAULT 'Backlog',
TaskPosition INT NOT NULL, 
TaskTitle VARCHAR(200) NOT NULL,
TaskDescription TEXT NOT NULL,
Priority task_priority NOT NULL DEFAULT 'Medium',
AssigneeId INT,
DueDate DATE NOT NULL,
CreatedBy INT NOT NULL,
CreatedAt TIMESTAMP DEFAULT NOW(),
CONSTRAINT fk_taskassignee FOREIGN KEY (AssigneeId) REFERENCES Users(UserId),
CONSTRAINT fk_taskcreator FOREIGN KEY (CreatedBy) REFERENCES Users(UserId),
CONSTRAINT fk_project FOREIGN KEY (ProjectId) REFERENCES Projects(ProjectId)
);

CREATE TABLE CommentsTable (
CommentId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
TaskId INT NOT NULL,
UserId INT NOT NULL,
Comment TEXT NOT NULL,
CreatedAt TIMESTAMP DEFAULT NOW(),
CONSTRAINT fk_user FOREIGN KEY (UserId) REFERENCES Users(UserId),
CONSTRAINT fk_task FOREIGN KEY (TaskId) REFERENCES Tasks(TaskId)
);

CREATE TABLE TaskHistory(
HistoryId INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
TaskId INT NOT NULL,
UserId INT NOT NULL,
Actions VARCHAR (80),
OldValue JSONB NOT NULL,
NewValue JSONB NOT NULL,
CreatedAt TIMESTAMP DEFAULT NOW()
);